name = "Cobbleverse NeoForge Zen"
author = "Zen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac34ed48758af3903b54a38a845ab150f8badb04d2896f0efe2b755cc9fe1a3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1", "1.21", "1.20.1"]
