name = "Cobbleverse NeoForge Zen"
author = "Zen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "074f47e72941c54f3cd46a4a1b84eefa8567ec3444175e55db37515da0b95d41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1", "1.21", "1.20.1"]
