version = 1
enableSodiumMenu = false
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = false
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 64
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
comforts = true
lumymon = true
cobblemonbattlepositions = true
cobblecuisine = true
tmcraft = true
rctmod = true
cobblefurnies = true
moarconcrete = true
sophisticatedstorage = true
pokeblocks = true
cozyhome = true
beautify = true
waystones = true
cobblemon-additions = true
handcrafted = true
carved_wood = true
mega_showdown = true
cobblemon = true
sophisticatedbackpacks = true
toms_storage = true
legendarymonuments = true
minecraft = true
rechiseled = true
